In [7]:
import pickle
import numpy as np

In [2]:
with open("weights.pkl", "rb") as f:
    weights = pickle.load(f)

In [9]:
blank_model = []
for layer in weights:
    print(layer.shape)
    blank_model.append(np.zeros(layer.shape))

(3, 3, 3, 64)
(64,)
(64,)
(64,)
(64,)
(3, 3, 64, 64)
(64,)
(64,)
(64,)
(64,)
(3, 3, 64, 64)
(64,)
(64,)
(64,)
(64,)
(3, 3, 64, 64)
(64,)
(64,)
(64,)
(64,)
(3, 3, 64, 64)
(64,)
(64,)
(64,)
(64,)
(3, 3, 64, 128)
(128,)
(128,)
(128,)
(128,)
(3, 3, 128, 128)
(128,)
(128,)
(128,)
(128,)
(1, 1, 64, 128)
(128,)
(128,)
(128,)
(128,)
(3, 3, 128, 128)
(128,)
(128,)
(128,)
(128,)
(3, 3, 128, 128)
(128,)
(128,)
(128,)
(128,)
(3, 3, 128, 256)
(256,)
(256,)
(256,)
(256,)
(3, 3, 256, 256)
(256,)
(256,)
(256,)
(256,)
(1, 1, 128, 256)
(256,)
(256,)
(256,)
(256,)
(3, 3, 256, 256)
(256,)
(256,)
(256,)
(256,)
(3, 3, 256, 256)
(256,)
(256,)
(256,)
(256,)
(3, 3, 256, 512)
(512,)
(512,)
(512,)
(512,)
(3, 3, 512, 512)
(512,)
(512,)
(512,)
(512,)
(1, 1, 256, 512)
(512,)
(512,)
(512,)
(512,)
(3, 3, 512, 512)
(512,)
(512,)
(512,)
(512,)
(3, 3, 512, 512)
(512,)
(512,)
(512,)
(512,)
(512, 10)
(10,)
()
()
()
()
()
()
()
()


In [12]:
for layer in blank_model:
    print(layer.shape)
    print(layer)
    break

(3, 3, 3, 64)
[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]]


In [11]:
with open("../../server/testweight_v1.pkl", "wb") as f:
    pickle.dump(blank_model, f)

In [14]:
len(blank_model)

110